#!/bin/bash
set -e

# Display usage information
usage() {
    echo "Usage: podcast [-d] [-r <URL>] [-f <file>] <episode-args...>"
    echo ""
    echo "Options:"
    echo "  -d              Enable debug mode"
    echo "  -r <URL>        RSS feed URL to download from"
    echo "  -f <file>       Local path to RSS feed file"
    echo "  -h              Display this help message"
    echo "  <episode-args>  Episode arguments (start/end range, comma-separated list, etc.)"
    echo ""
    echo "Examples:"
    echo "  podcast -r 'http://example.com/rss' 1-5"
    echo "  podcast -f 'rss' 1,3,5"
    echo "  podcast -d -r 'http://example.com/rss' 1"
}

# Parse arguments using getopts
while getopts ":dh:r:f:" opt; do
    case $opt in
        d)
            DEBUG="true"
            ;;
        r)
            RSS_URL="$OPTARG"
            ;;
        f)
            RSS_FILE="$OPTARG"
            ;;
        h)
            usage
            exit 0
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

# Check if we have remaining arguments (episode args)
if [ $# -eq 0 ]; then
    usage
fi

EPI_START="$1"
EPI_END="${2:-}"


# -----------------
# Argument Assembly
# -----------------
# Assemble the arguments based on how we intend to use them

if [ -n "RSS_FILE" ]; then
    ARGS=("cat")
    ARGS+=("$RSS_FILE")
    ARGS+=("|")
    ARGS+=("docker")
else
    ARGS=("docker")
fi

ARGS+=("run")
ARGS+=("--rm")
ARGS+=("-i")
ARGS+=("podcast-dl:latest")

if [ -n "$DEBUG" ]; then
    ARGS+=("-d")
fi

if [ -n "$RSS_URL" ]; then
    ARGS+=("-r")
    ARGS+=("$RSS_URL")
fi

TAR=
if [ -n "$EPI_START" ]; then
    ARGS+=("$EPI_START")
    TAR=true
fi

if [ -n "$EPI_END" ]; then
    ARGS+=("$EPI_END")
    TAR=true
fi

if [ -n "$TAR" ]; then
    ARGS+=("|")
    ARGS+=("tar")
    ARGS+=("-xvf")
    ARGS+=("-")
fi

eval ${ARGS[@]}